eureka:
  client:
    service-url:
      defaultZone: http://peer1:20001/eureka/,http://peer2:20002/eureka/
feign:
  hystrix:
    enabled: true
feign-client:
  ribbon:
    ConnectTimeout: 1000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
    ReadTimeout: 8000
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        errorThresholdPercentage: 50
        forceClosed: false
        forceOpen: false
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 15000
      execution:
        isolation:
          thread:
            interruptOnFutureCancel: true
            interruptOnTimeout: true
            timeoutInMilliseconds: 4000
        timeout:
          enabled: true
      fallback:
        enabled: true
      metrics:
        rollingStats:
          timeInMilliseconds: 20000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 50000
spring:
  application:
    name: hystrix-consumer
  main:
    allow-bean-definition-overriding: true
