spring:
  application:
    name: eureka-client
server:
  port: 30000
eureka:
  client:
    service-url:
      defaultZone: http://peer1:20001/eureka/,http://peer2:20002/eureka/
  instance:
    #每隔5秒向服务注册中心发送一条续约指令
    lease-renewal-interval-in-seconds: 5
    #如果30秒内，依然没有收到续约请求，判定服务过期
    lease-expiration-duration-in-seconds: 30
