spring:
  application:
    name: hystrix-turbiner
server:
  port: 52000
management:
  server:
    port: 52001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:20001/eureka/,http://peer2:20002/eureka/
turbine:
  app-config: hystrix-consumer   #指定所需要监控的服务名
  cluster-name-expression: new String('default')
  combine-host-port: true  #将端口和hostname作为区分不同服务的条件（默认只使用host）
  instanceUrlSuffix:
    default: actuator/hystrix.stream
  aggregator:
    cluster-config: default





